spring:
  profiles:
    active: dev
  data:
    mongodb:
      hostname: localhost
      port: 27017
      username: admin
      password: adminpassword
      database: betterbanking
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9001/realms/open-banking-realm/protocol/openid-connect/certs
resilience4j:
  circuitbreaker:
    instances:
      transactionService:
        failureRateThreshold: 100
        waitDurationInOpenState: 10s
        slidingWindowSize: 1 # Consider only the last call
        minimumNumberOfCalls: 1 # Even one call is enough
        automaticTransitionFromOpenToHalfOpen: true
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.example: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %5p [%logger{1}] %m%n"
