application:
  open-banking:
    base-uri: http://localhost:9080
spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      hostname: localhost
      port: 27017
      username: admin
      password: adminpassword
      database: betterbanking
      authentication-database: admin
  cache:
    type: redis
    time-to-live: PT10M
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:9001/realms/open-banking-realm/protocol/openid-connect/certs}
      client:
        registration:
          better-banking:
            grant_type: client_credentials
            authorisation: "Basic yOo5wZwkzPDCvI2GgWwYNO7w0bHGRTfS"
        provider:
          better-banking:
            token-uri: http://localhost:9080/oauth/token
resilience4j:
  circuitbreaker:
    instances:
      transactionService:
        failureRateThreshold: 100
        waitDurationInOpenState: 10s
        slidingWindowSize: 1 # Consider only the last call
        minimumNumberOfCalls: 1 # Even one call is enough
        automaticTransitionFromOpenToHalfOpen: true
logging:
  level:
    root: INFO
    org.springframework.data.redis: DEBUG
    io.betterbanking: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %5p [%logger{1}] %m%n"
