services:
  better-banking:
    container_name: bb
    image: betterbanking
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_REDIS_HOST: redis
      # acme-banking
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_BETTER_BANKING_TOKEN_URI: http://acme-banking:8080/oauth/token
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BETTER_BANKING_AUTHORISATION: "Basic YmV0dGVyLWJhbmtpbmc6N3lyYlI4WHBZNDViY0tQUA=="
      APPLICATION_OPEN_BANKING_BASE_URI: http://acme-banking:8080
      # keycloak
      JWK_SET_URI: http://kc:8080/realms/open-banking-realm/protocol/openid-connect/certs
    networks:
      - internal
      - external

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - internal

  acme-banking-db:
    container_name: acme-banking-db
    image: 'mysql/mysql-server:latest'
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=acme
    restart: always
    networks:
      - internal

  acme-banking:
    container_name: acme-banking
    image: nathanbcrocker/acme-testnet
    ports:
      - 9080:8080
    restart: on-failure
    depends_on:
      acme-banking-db:
        condition: service_healthy
    environment:
      - co.uk.bankcorp.client=better-banking
      - co.uk.bankcorp.secret=7yrbR8XpY45bcKPP
      - MYSQL_HOST=acme-banking-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=acme
      - DATABASE_PORT=3306
      - SERVER_PORT=8080
    networks:
      - internal

volumes:
  mongodb_data:

networks:
  internal:
    name: better-banking
  external:
    name: docker-keycloak_default
    external: true
