spring:
  application:
    name: betterbanking
  data:
    mongodb:
      host: localhost
      port: 27017
      database: betterbanking
      username: admin
      password: adminpassword
      authentication-database: admin
